name: "Code-Style Fix"

on:
    push:
        branches: [ master ]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Checking PHP Syntax
                uses: TheDragonCode/php-codestyler@latest
                with:
                    fix: true
